name: bitbot
version: '0.4'
summary: Bitrix24 voice assistant # 79 char long summary
description: |
  This app can detect keyword and send next voice record to the cloud,
  recognized command will send to Bitrix24. This app bugger aware.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
icon: ./icon.png
apps:
  continuous:
    command: python $SNAP/continuous.py
    daemon: simple
    environment:
      ALSA_CONFIG_PATH: $SNAP/usr/share/alsa/alsa.conf
    restart-condition: always
    plugs:
      - network
      - pulseaudio
      - alsa
      
  webserver:
    command: python $SNAP/webserver.py -p 8080
    daemon: simple
    restart-condition: always
    plugs: [network-bind]

parts:

  acoustic-model:
#    source: https://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/US%20English/cmusphinx-en-us-5.2.tar.gz
#    source: https://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/Russian/cmusphinx-ru-5.2.tar.gz
    source: hmm/cmusphinx-ru-5.2.tar.gz
    plugin: dump
    organize:
      '*': hmm/
    stage:
      - -hmm/*.lm
      - -hmm/*.dic
      - -hmm/*.lm.bin
      - -*.lm
      - -*.dic
      - -*.lm.bin
    prime:
      - -hmm/*.lm
      - -hmm/*.dic
      - -hmm/*.lm.bin
      - -*.lm
      - -*.dic
      - -*.lm.bin

  assets:
    source: assets/
    plugin: dump

  continuous-pip-packages:
    plugin: python
    source: continuous/
    python-version: python2
    stage-packages:
      - libc6
    python-packages:
      - pygame

  continuous:
    after: [continuous-pip-packages]
    source: continuous/
    plugin: dump
    stage-packages:
      - python-pocketsphinx
      - python-sphinxbase
      - libc6
      - portaudio19-dev
      - python-pyaudio

  config-webserver:
    source: configserver/
    plugin: dump