name: bitbot
version: '0.4'
summary: Bitrix24 voice assistant # 79 char long summary
description: |
  This app can detect keyword and send next voice record to the cloud,
  recognized command will send to Bitrix24. This app bugger aware.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
icon: ./icon.png
apps:
  bitbot:
    command: continuous.py
#    environment:
#      LD_LIBRARY_PATH: $SNAP/lib
#      PKG_CONFIG_PATH: $SNAP/lib/pkgconfig
    daemon: simple
    restart-condition: always
    plugs:
      - network
      - alsa
      
  conf-server:
    command: webserver -p 80 www
    daemon: simple
    restart-condition: always
    plugs: [network-bind]

parts:

  acoustic-model:
#    source: https://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/US%20English/cmusphinx-en-us-5.2.tar.gz
    source: https://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/Russian/cmusphinx-ru-5.2.tar.gz
#    source: hmm/cmusphinx-ru-5.2.tar.gz
    plugin: dump
    organize:
      '*': hmm/
    stage:
      - -hmm/*.lm
      - -hmm/*.dic
      - -hmm/*.lm.bin
      - -*.lm
      - -*.dic
      - -*.lm.bin
    prime:
      - -hmm/*.lm
      - -hmm/*.dic
      - -hmm/*.lm.bin
      - -*.lm
      - -*.dic
      - -*.lm.bin

  assets:
    source: assets/
    plugin: dump

  continuous:
    source: continuous/
    plugin: dump

  config-webserver:
    plugin: go
    source: .
    go-importpath: github.com/1os/bitbot/config-webserver-part

  sphinxbase:
    plugin: autotools
    source: https://sourceforge.net/projects/cmusphinx/files/sphinxbase/5prealpha/sphinxbase-5prealpha.tar.gz
#    source: sphinxbase-5prealpha.tar.gz
    build-packages:
      - bison
      - libasound2-dev
      - alsa-utils
      - swig
      - python-dev
    stage-packages:
      - bison
      - libasound2-dev
      - alsa-utils
      - swig
      - python-dev
      - libc6
      - python-pyaudio
    configflags:
      - --enable-fixed
      - --prefix=/
    after:
      - config-webserver
      
  pocketsphinx:
    plugin: autotools
    source: https://sourceforge.net/projects/cmusphinx/files/pocketsphinx/5prealpha/pocketsphinx-5prealpha.tar.gz
#    source: pocketsphinx-5prealpha.tar.gz
    override-build: |
      export PKG_CONFIG=$SNAPCRAFT_STAGE
      snapcraftctl build
    configflags:
      - --enable-fixed
      - --prefix=/
    after:
      - sphinxbase
    build-packages:
      - bison
      - libasound2-dev
      - alsa-utils
      - swig
      - python-dev
      - pkg-config
    stage-packages:
      - bison
      - libasound2-dev
      - alsa-utils
      - swig
      - python-dev
      - libc6
      - pkg-config